POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ildvd2llIiwiaWQiOiI2MzRkYzlhOTZlZDM2YzI1MTZiMTYwMTAiLCJpYXQiOjE2NjYwNDIyODV9.Wdb3oUtQ8W7h6J9qI8ypzw2LYnNU7hv50yzL-d5HeJA

{
  "title": "REST testing in a nutshell",
  "author": "Me",
  "url": "http://localhost:3003/api/blogs",
  "likes": 1
}
